name: Pre-release

run-name: Pre-release ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - 'v*'

jobs:
  create_pre_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" -p

  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Build
        run: go generate

      - name: Upload files (MacOS arm64)
        if: ${{ matrix.platform == 'macos-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: darwin
          ARCH: arm64
        run: |
          tar cvzf "ern-overlay-${{ env.OS }}-${{ env.ARCH }}.tar.gz" -C "dist/${{ env.OS }}/${{ env.ARCH }}" .
          gh release upload "${{ github.ref_name }}" "ern-overlay-${{ env.OS }}-${{ env.ARCH }}.tar.gz"

      - name: Upload files (Windows amd64)
        if: ${{ matrix.platform == 'windows-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: windows
          ARCH: amd64
        run: |
          tar cvzf "ern-overlay-${{ env.OS }}-${{ env.ARCH }}.tar.gz" -C "dist/${{ env.OS }}/${{ env.ARCH }}" .
          gh release upload "${{ github.ref_name }}" "ern-overlay-${{ env.OS }}-${{ env.ARCH }}.tar.gz"
